package com.muddassir.clearview.goodpost.data

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Encrypted-at-rest storage for the Good Post session (§3: "secure token
 * storage on Android").
 *
 * Implemented directly on the Android Keystore rather than with
 * `androidx.security:security-crypto`. That library — and
 * `EncryptedSharedPreferences` specifically — was deprecated at
 * 1.1.0-alpha07, and Google's own guidance is to use the Keystore directly, so
 * pulling in a deprecated artifact to encrypt two short strings would trade a
 * real maintenance liability for a thin convenience wrapper.
 *
 * The AES-256-GCM key is generated inside the Keystore and never leaves it:
 * this code only ever holds the ciphertext and the IV. `setUserAuthenticationRequired`
 * is deliberately NOT set — requiring a biometric prompt to read a refresh
 * token would mean a fingerprint check on every token refresh, and the threat
 * this defends against (a stolen, still-locked device image) is not one that
 * a lock-screen prompt improves.
 *
 * The refresh token is the value worth protecting: an access token expires in
 * 15 minutes, whereas a refresh token is a 30-day credential. §3 forbids
 * keeping either in plaintext preferences.
 */
class SecureTokenStore(context: Context) {

    private companion object {
        const val TAG = "GoodPostTokenStore"

        const val PREFS_NAME = "clearview_goodpost_auth"
        const val KEY_PAYLOAD = "session_payload"

        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val KEY_ALIAS = "clearview_goodpost_session_key"
        const val TRANSFORMATION = "AES/GCM/NoPadding"

        /** 128-bit authentication tag: the GCM maximum. */
        const val TAG_LENGTH_BITS = 128

        const val SEPARATOR = ":"
    }

    private val prefs =
        context.applicationContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    /**
     * Persist the session. A failure here is logged and swallowed rather than
     * thrown: the in-memory session still works for this run, and crashing on
     * a device with an unhealthy Keystore would be worse than making the user
     * sign in again after a restart.
     */
    fun save(session: GoodPostSession) {
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(Cipher.ENCRYPT_MODE, secretKey())
            }
            val encrypted = cipher.doFinal(
                GoodPostSessionCodec.encode(session).toByteArray(Charsets.UTF_8)
            )

            // The IV must be stored alongside the ciphertext — but it is not a
            // secret, and GCM refuses to reuse one with the same key, so it is
            // regenerated by the cipher on every save.
            val payload = base64(cipher.iv) + SEPARATOR + base64(encrypted)
            prefs.edit().putString(KEY_PAYLOAD, payload).apply()
        } catch (e: Exception) {
            Log.e(TAG, "Could not persist the Good Post session: ${e.message}")
        }
    }

    /**
     * Read the stored session, or null when there is none.
     *
     * Every failure path ends in [clear]. A Keystore key can legitimately
     * become undecryptable (the user resets their lock screen, the key is
     * invalidated, the OS rekeys on a security patch), and the correct
     * response to unreadable credentials is to forget them and ask for the
     * phone number again — never to throw on every app start.
     */
    fun load(): GoodPostSession? {
        val payload = prefs.getString(KEY_PAYLOAD, null)
        if (payload.isNullOrBlank()) return null

        val parts = payload.split(SEPARATOR)
        if (parts.size != 2) {
            clear()
            return null
        }

        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(
                    Cipher.DECRYPT_MODE,
                    secretKey(),
                    GCMParameterSpec(TAG_LENGTH_BITS, unbase64(parts[0]))
                )
            }
            val plain = String(cipher.doFinal(unbase64(parts[1])), Charsets.UTF_8)

            // A successful decrypt that decodes to null means the stored JSON
            // predates a format change; treat it as signed out.
            GoodPostSessionCodec.decode(plain).also { if (it == null) clear() }
        } catch (e: Exception) {
            Log.w(TAG, "Stored session is unreadable, discarding it: ${e.message}")
            clear()
            null
        }
    }

    /**
     * Remove the stored session. The Keystore key is intentionally left in
     * place: deleting it would invalidate nothing else, and keeping it means
     * signing back in does not have to regenerate one.
     */
    fun clear() {
        prefs.edit().remove(KEY_PAYLOAD).apply()
    }

    // ── Internals ───────────────────────────────────────────────────────

    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let {
            return it.secretKey
        }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                // GCM must never be used with a repeated IV, so the Keystore is
                // told to randomise it per operation rather than accepting one.
                .setRandomizedEncryptionRequired(true)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }

    private fun base64(bytes: ByteArray): String = Base64.encodeToString(bytes, Base64.NO_WRAP)

    private fun unbase64(value: String): ByteArray = Base64.decode(value, Base64.NO_WRAP)
}
